### PR TITLE
Upgrade to Jetty 12.0.0 release

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

#### Changes proposed in this pull request:

-
-
-

**Fixes**: #

### CODE REVIEW

**Review by joakime — APPROVED** [review]

**Comment by olamy** [comment]
@starksm64 Could you please cut a new release with this change? Thanks

**Comment by chengfang** [comment]
@olamy you might want to upgrade arquillian-core to 1.7.1.Final (https://github.com/arquillian/arquillian-core/releases/tag/1.7.1.Final)  before the release. 1.7.1.Final contains a fix to a validation error in arquillian-bom.  Looks like the dependobot (weekly) hasn't picked it up yet.

**Comment by olamy** [comment]
@chengfang good catch.

**Comment by olamy** [comment]
@chengfang dependabot manual run gave this one https://github.com/arquillian/arquillian-container-jetty/pull/150  :)

**Comment by chengfang** [comment]
@olamy great, looks everything is ready. I'll prepare the next 2.0.0.Final release.

**Pull request merged**
