### PR TITLE
Update to Arquillian Core 1.1.8.Final

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by janbartel** [comment]
I don't know where the full setup of jetty is for that test case, so I can't verify this myself. But, if you've already tried putting in bad formatting into the jetty-env.xml file and checked that no error is thrown, then it sounds like the file is not being read. That file is read by the org.eclipse.jetty.plus.webapp.EnvConfiguration class, that is configured onto the WebAppContext. The example of how to do the setup that class in code is here: https://github.com/eclipse/jetty.project/blob/master/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ServerWithJNDI.java.   The alternative setup of that class via an xml file that is applied to the Server instance is here: https://github.com/eclipse/jetty.project/blob/master/jetty-plus/src/main/config/etc/jetty-plus.xml.

cheers
Jan

**Comment by aslakknutsen** [comment]
@janbartel The Jetty instance is setup here; https://github.com/arquillian/arquillian-container-jetty/blob/master/jetty-embedded-9/src/main/java/org/jboss/arquillian/container/jetty/embedded_9/JettyEmbeddedContainer.java#L165

**Comment by janbartel** [comment]
@aslakknutsen seems fine on a cursory look at that link.

You can call server.setDumpAfterStart(true) and that will print out the entire setup of the server and webapps after the server starts, and you should see output for the webapp context that lists all of the Configuration objects set up on it - that way you can confirm whether or not the EnvConfiguration is being applied to the webapp.

If its listed, but the file is not being read (verified by placing some non-xml parseable statement in the jetty-env.xml file), then possibly the location of the jetty-env.xml file is incorrect. It should be either be set explicitly on the EnvConfiguration with setJettyEnvXml(URL), or inside the WEB-INF directory. 

Jan

 Can you enable jetty debug logging for the package (this is normally by setting the system property -Dorg.eclipse.jetty.plus.webapp=DEBUG, but I'm not sure how you've setup the logging environment, so you may need to do the equivalent in some other logging system). You should see log output from the EnvConfiguration class that will show its being executed at least. If you see output from it, but the jetty-env.xml file is not being read, then possibly it is not at the location you think it is (ie it should be inside of WEB-INF).  If you don't see any output from it, then the setup of the list of Configuration classes is not correct. 

Jan

**Comment by aslakknutsen** [comment]
@janbartel ha! Found it! https://github.com/arquillian/arquillian-container-jetty/pull/22/files#diff-7a58ada16e8a71ce5281b026d647adceR141 :beers: 

Helps to actually apply the configuration objects to the same ClassList instance as the server use, not just some other willy nilly instance :)

Thanks for the help! Highly appreciated!

**Comment by aslakknutsen** [comment]
Pushed upstream https://github.com/arquillian/arquillian-container-jetty/commit/7f30465ebeaf4d33c4ec4e62f636cc54f015a772

**Pull request closed without merging**
