### PR TITLE
add release drafter to get fancy release notes

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

#### Changes proposed in this pull request:

-
-
-

**Fixes**: #

### CODE REVIEW

**Review by bartoszmajsak — APPROVED** [review]
Sure, why not :)

**Comment by bartoszmajsak** [comment]
@olamy I guess we need to set `GITHUB_TOKEN`. I don't see it set yet in `secrets/actions`.

**Comment by olamy** [comment]
> Sure, why not :)

haha 🤣
have a look here https://github.com/arquillian/arquillian-container-jetty/releases

**Comment by olamy** [comment]
> @olamy I guess we need to set `GITHUB_TOKEN`. I don't see it set yet in `secrets/actions`.

nah

**Comment by bartoszmajsak** [comment]
> > @olamy I guess we need to set `GITHUB_TOKEN`. I don't see it set yet in `secrets/actions`.
> 
> nah

Ok, then why do we have it in YAML? :)

**Comment by olamy** [comment]
> > > @olamy I guess we need to set `GITHUB_TOKEN`. I don't see it set yet in `secrets/actions`.
> > 
> > 
> > nah
> 
> Ok, then why do we have it in YAML? :)

it's a special token. you can read some details here https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp

**Pull request merged**
